### ISSUE TITLE
Reference ID LCL vs. GPS

### ISSUE THREAD

**Issue by michaelwingender** [PublicNTP/time-server-app#11]
Hello,
Currently if I start the NTP server on a device where I installed the App, clients recognise the NTP server as Undisciplined Local Clock (LCL). Wouldn't it make sense to set Reference ID to GPS?

BR
Michael

**Comment by swaddell** [comment]
Micheal,
Great suggestion. This is coming in our next release. Hopefully, next week.

Cheers, Scott
