### ISSUE TITLE
Feature request: Automatically start SNTP server after booting the device and/or starting the App

### ISSUE THREAD

**Issue by michaelwingender** [PublicNTP/time-server-app#12]
Hello,
In my eyes it would be a good idea to have a switch in the App to automatically start the SNTP server at least after starting the App or better after booting of the Android device has finished. This should be a setting which can be turned on or off.

BR

**Comment by dzhub** [comment]
I would expect automatic restart from a server too :-)
I am trying to accomplish this using Tasker, but I cant figure out
how to send the right "intent" to Time Server App.

To me, it seems like It should accept intents using `app.timeserver.service.ntp.NtpService`, but I cant get the App to start the SNTP server.

**Comment by swaddell** [comment]
We totally agree! Auto-start will be a feature on our next release. Hopefully, if testing goes well, we will release next week.

Cheers, Scott
